version: "3"
services:
  db:
    image: postgres:11.13
    container_name: traceTogether-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
volumes:
  postgres_data: {}