version: '3.1'

services:
  db:
    image: postgres:10.23-alpine3.16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trace_together_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    image: trace-together-local:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db/trace_together_db
      DB_USERNAME: postgres
      DB_PASSWORD: password
      SPRING_PROFILES_ACTIVE: container