spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: mysecretpassword
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
