spring:
  datasource:
    url: jdbc:postgresql://db:5432/mydb
    username: myuser
    password: mypassword
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        globally-quoted-identifiers: true
        globally-quoted-identifiers-skip-column-definitions: true
  sql:
    init:
      mode: always
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
